name: found_lost_app
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get:
  get_storage:
  introduction_screen:
  bubble_bottom_bar:
  pinput: ^2.2.12
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.1
  cloud_firestore: ^4.2.0
  firebase_storage: ^11.0.8
  firebase_analytics: ^10.0.7
  uuid: ^3.0.7
  image_picker: ^0.8.6
  cached_network_image: ^3.2.3



  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:
flutter_icons:
  image_path: "assets/images/main_logo.png"
  android: true
  ios: true
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: IBM
      fonts:
        - asset: assets/fonts/IBMPlexSansArabic-Medium.ttf
    - family: Sofia Pro
      fonts:
        - asset: assets/fonts/sofia/Sofia_Pro_Bold.ttf
        - weight: 700
        - asset: assets/fonts/sofia/Sofia_Pro_SemiBold.ttf
        - weight: 600
        - asset: assets/fonts/sofia/Sofia_Pro_Medium.ttf
        - weight: 500
        - asset: assets/fonts/sofia/Sofia_Pro_Regular.ttf
        - weight: 400    
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-package